version: "3"

volumes:
  bakecode:
    driver: local
  mosquitto:
    driver: local

services:
  bakecode:
    image: bakecode:latest
    container_name: bakecode
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
      - 8883:8883
    volumes:
      - mosquitto:/etc/mosquitto
