name: bakecode

description: bakecode ecosystem engine

version: 0.0.1-alpha

publish_to: none

repository: https://github.com/osumpi/bakecode
issue_tracker: https://github.com/osumpi/bakecode/issues

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.2.0
  bsi_dart:
    git: https://github.com/osumpi/bsi-dart.git
  console: ^4.1.0
  equatable: ^2.0.0
  hive: ^2.0.4
  intl: ^0.17.0
  logging: ^1.0.1
  pubspec_parse: ^1.0.0
  uuid: ^3.0.4
  yaml: ^3.1.0

dev_dependencies:
  lint: ^1.5.3
  meta: ^1.7.0
