name: bakecode_ecosystem_runtime
description: BakeCode Ecosystem Runtime
version: 0.0.1-alpha
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies: 
  bakecode:
    git: git@github.com:crysalisdevs/bakecode.git
  bsi:
    git: git@github.com:crysalisdevs/bsi-dart.git
  args: ^1.6.0
  meta:
  logger:
  equatable:
