name: bakecode_ecosystem_runtime
description: BakeCode Ecosystem Runtime
version: 0.0.1-alpha

publish_to: none

# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bakecode:
    git: git@github.com:crysalisdevs/bakecode.git
  bsi:
    git: git@github.com:crysalisdevs/bsi-dart.git
  args: ^2.0.0
  meta: ^1.3.0
  equatable: ^2.0.0
  hotreloader: ^3.0.0
  cli_repl: ^0.2.2
