name: bakecode
description: BakeCode Gateway Service.
version: 0.0.1-alpha
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies: 
  bakecode_jobs:
    path: bakecode-jobs/
  bsi_dart:
    path: bsi-dart/
  args: ^1.6.0
  meta:
  logger:
  get_it:
  equatable:
  event_bus:
  mqtt_client:
  json_serializable:

dev_dependencies:
  build_test:
  build_runner:
  pedantic: ^1.9.0
