name: bakecode_engine
description: BakeCode Ecosystem Runtime
version: 0.0.1-alpha

publish_to: none

# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  args: ^2.2.0
  checked_yaml: ^2.0.1
  console: ^4.1.0
  core:
    git: git@github.com:bakecode-devs/core.git
  equatable: ^2.0.0
  hotreloader: ^3.0.0
  json_annotation: ^4.1.0
  pubspec_parse: ^1.0.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^5.0.0
  lint: ^1.5.3
  meta: ^1.7.0