name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # Setup Java environment in order to build the Android app.
    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - name: Install Flutter
      uses: subosito/flutter-action@v1.3.2
      with:
        # The Flutter version to make available on the path
        flutter-version: 1.20.0-2.0.pre # optional
        # The Flutter build release channel
        channel: dev # optional, default is stable

    # Get flutter dependencies.
    - name: Install Flutter Dependencies
      run: flutter pub get
    
    # Statically analyze the dart code for any errors.
    - name: Analyze Code
      run: flutter analyze .

    # Enable Web Support
    - name: Enable Web Support
      run: flutter config --enable-web

    # Build web.
    - name: Build Web
      run: flutter build web --release --tree-shake-icons
