name: Document Generation

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_dartdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dartdoc