name: Documentation

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_dartdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - uses: cedx/setup-dart@v2.3.0
      - run: dartdoc
