name: Documentation

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_dartdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - uses: cedx/setup-dart@v2.3.0
      - run: dartdoc
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v5.2.0
        with:
          author_name: DocBot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
